-   id: pytype
    name: pytype
    entry: pytype
    language: python
    'types': [python]
    args: ["--config=pytype.cfg","--ignore-missing-imports",]
    require_serial: true
    additional_dependencies: []
